# Generated by Django 6.0.1 on 2026-02-26 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_options_post_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.AlterField(
            model_name='post',
            name='upadated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
