# Generated by Django 6.0.1 on 2026-03-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upadated_at',
            new_name='updated_at',
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(unique_for_date='publish'),
        ),
    ]
