# Generated by Django 6.0.2 on 2026-03-19 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_post_slug'),
        ('blog', '0009_rename_upadated_at_post_updated_at_alter_post_slug'),
    ]

    operations = [
    ]
